
package com.mycompany.horus.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueServicePortType", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueServicePortType {


    /**
     * Retorna a posição de estoque por número CNES do estabelecimento de Saúde.
     * 
     * @param requestConsultarPosicaoEstoquePorCNES
     * @return
     *     returns com.gatewayedi.ws.ResponseConsultarPosicaoEstoquePorCNES
     * @throws EstoqueFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarPosicaoEstoquePorCNES", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "responseConsultarPosicaoEstoquePorCNES")
    public ResponseConsultarPosicaoEstoquePorCNES consultarPosicaoEstoquePorCNES(
        @WebParam(name = "requestConsultarPosicaoEstoquePorCNES", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "requestConsultarPosicaoEstoquePorCNES")
        RequestConsultarPosicaoEstoquePorCNES requestConsultarPosicaoEstoquePorCNES)
        throws EstoqueFault
    ;

    /**
     * Retorna a posição de estoque por número CNES do estabelecimento de Saúde.
     * 
     * @param requestConsultarPosicaoEstoquePorCNESPrincipioAtivo
     * @return
     *     returns com.gatewayedi.ws.ResponseConsultarPosicaoEstoquePorCNESPrincipioAtivo
     * @throws EstoqueFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarPosicaoEstoquePorCNESPrincipioAtivo", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "responseConsultarPosicaoEstoquePorCNESPrincipioAtivo")
    public ResponseConsultarPosicaoEstoquePorCNESPrincipioAtivo consultarPosicaoEstoquePorCNESPrincipioAtivo(
        @WebParam(name = "requestConsultarPosicaoEstoquePorCNESPrincipioAtivo", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "requestConsultarPosicaoEstoquePorCNESPrincipioAtivo")
        RequestConsultarPosicaoEstoquePorCNESPrincipioAtivo requestConsultarPosicaoEstoquePorCNESPrincipioAtivo)
        throws EstoqueFault
    ;

    /**
     * Retorna a posição de estoque por número CNES do estabelecimento de Saúde, de forma paginada.
     * 
     * @param requestConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado
     * @return
     *     returns com.gatewayedi.ws.ResponseConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado
     * @throws EstoqueFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "responseConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado")
    public ResponseConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado consultarPosicaoEstoquePorCNESPrincipioAtivoPaginado(
        @WebParam(name = "requestConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "requestConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado")
        RequestConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado requestConsultarPosicaoEstoquePorCNESPrincipioAtivoPaginado)
        throws EstoqueFault
    ;

    /**
     * Retorna a posição de estoque por número CNES que dispensou o medicamento.
     * 
     * @param requestConsultarProdutoPorCNESDispensacao
     * @return
     *     returns com.gatewayedi.ws.ResponseConsultarProdutoPorCNESDispensacao
     * @throws EstoqueFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarProdutoPorCNESDispensacao", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "responseConsultarProdutoPorCNESDispensacao")
    public ResponseConsultarProdutoPorCNESDispensacao consultarProdutoPorCNESDispensacao(
        @WebParam(name = "requestConsultarProdutoPorCNESDispensacao", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "requestConsultarProdutoPorCNESDispensacao")
        RequestConsultarProdutoPorCNESDispensacao requestConsultarProdutoPorCNESDispensacao)
        throws EstoqueFault
    ;

    /**
     * Retorna a posição de estoque por número CNES que dispensou o medicamento, de forma Paginada.
     * 
     * @param requestConsultarProdutoPorCNESDispensacaoPaginado
     * @return
     *     returns com.gatewayedi.ws.ResponseConsultarProdutoPorCNESDispensacaoPaginado
     * @throws EstoqueFault
     */
    @WebMethod
    @WebResult(name = "responseConsultarProdutoPorCNESDispensacaoPaginado", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "responseConsultarProdutoPorCNESDispensacaoPaginado")
    public ResponseConsultarProdutoPorCNESDispensacaoPaginado consultarProdutoPorCNESDispensacaoPaginado(
        @WebParam(name = "requestConsultarProdutoPorCNESDispensacaoPaginado", targetNamespace = "http://servicos.saude.gov.br/horus/v1r0/EstoqueService", partName = "requestConsultarProdutoPorCNESDispensacaoPaginado")
        RequestConsultarProdutoPorCNESDispensacaoPaginado requestConsultarProdutoPorCNESDispensacaoPaginado)
        throws EstoqueFault
    ;

}
